/* 
    90 Productos

    Requiere:
        idCategoria >= 20
*/
use pharmatic
insert into Producto (idCategoria, nombre, descripcion) values (13, 'Oxymetazoline Hydrochloride', 'United Exchange Corp.');
insert into Producto (idCategoria, nombre, descripcion) values (1, 'Alcohol', 'DSHealthcare');
insert into Producto (idCategoria, nombre, descripcion) values (6, 'Cimetidine', 'Carilion Materials Management');
insert into Producto (idCategoria, nombre, descripcion) values (4, 'AZITHROMYCIN MONOHYDRATE', 'Cardinal Health');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Hydroxyamphetamine', 'Akorn, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Methylprednisolone', 'DIRECT RX');
insert into Producto (idCategoria, nombre, descripcion) values (9, 'Promethazine Hydrochloride', 'REMEDYREPACK INC.');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'somatropin', 'EMD Serono, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (9, 'Irbesartan', 'Macleods Pharmaceuticals Limited');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'Neutral Sodium Fluoride', 'Oral-B Laboratories');
insert into Producto (idCategoria, nombre, descripcion) values (16, 'diclofenac potassium', 'Lake Erie Medical DBA Quality Care Products');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Atomoxetine hydrochloride', 'Cardinal Health');
insert into Producto (idCategoria, nombre, descripcion) values (13, 'Nicotine Polacrilex', 'Wal-Mart Stores Inc');
insert into Producto (idCategoria, nombre, descripcion) values (5, 'Oxaprozin', 'Carilion Materials Management');
insert into Producto (idCategoria, nombre, descripcion) values (11, 'Hydrocodone Bitartrate And Acetaminophen', 'Aphena Pharma Solutions - Tennessee, LLC');
insert into Producto (idCategoria, nombre, descripcion) values (8, 'Nitrogen', 'Linde Gas Puerto Rico, Inc');
insert into Producto (idCategoria, nombre, descripcion) values (13, 'Acetaminophen, Chlorpheniramine Maleate', 'Access Business Group LLC');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'lidocaine', 'Endo Pharmaceuticals Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (16, 'Hydroxyzine Pamoate', 'REMEDYREPACK INC.');
insert into Producto (idCategoria, nombre, descripcion) values (11, 'Naproxen Sodium', 'Rite Aid Corporation');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'SODIUM FLUORIDE F-18', 'Children''s Hospital of Michigan');
insert into Producto (idCategoria, nombre, descripcion) values (15, 'Terazosin Hydrochloride', 'REMEDYREPACK INC.');
insert into Producto (idCategoria, nombre, descripcion) values (10, 'Vitamin C, Calcium, Iron, Vitamin D3', 'Mission Pharmacal Company');
insert into Producto (idCategoria, nombre, descripcion) values (6, 'Hydrogen Peroxide', 'Kroger');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Titanium Dioxide', 'Coty US LLC');
insert into Producto (idCategoria, nombre, descripcion) values (10, 'Enoxaparin Sodium', 'Sandoz Inc');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'METOPROLOL SUCCINATE', 'Cardinal Health');
insert into Producto (idCategoria, nombre, descripcion) values (3, 'IBUPROFEN, .GAMMA.-AMINOBUTYRIC ACID', 'Physician Therapeutics LLC');
insert into Producto (idCategoria, nombre, descripcion) values (16, 'Acetaminophen and Diphenhydramine Hydrochloride', 'Eagle Distributors,Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (8, 'CYCLOSERINE', 'Purdue GMP Center LLC dba The Chao Center');
insert into Producto (idCategoria, nombre, descripcion) values (10, 'Chlorhexidine Gluconate', 'Colgate-Palmolive Company');
insert into Producto (idCategoria, nombre, descripcion) values (20, 'montelukast sodium', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC');
insert into Producto (idCategoria, nombre, descripcion) values (5, 'Acetaminophen', 'Kmart Corporation');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Hydroxyzine Hydrochloride', 'Clinical Solutions Wholesale');
insert into Producto (idCategoria, nombre, descripcion) values (16, 'tolnaftate', 'Rite Aid Corporation');
insert into Producto (idCategoria, nombre, descripcion) values (16, 'Celecoxib', 'Aidarex Pharmaceuticals LLC');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Cephalexin', 'Teva Pharmaceuticals USA Inc');
insert into Producto (idCategoria, nombre, descripcion) values (6, 'Indian Wormwood Sage', 'Antigen Laboratories, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Aluminum zirconium tetrachlorohydrex gly', 'Colgate-Palmolive Company');
insert into Producto (idCategoria, nombre, descripcion) values (2, 'Allergenic Extracts Alum Precipitated', 'ALK-Abello, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (11, 'BLEOMYCIN SULFATE', 'Hospira Worldwide, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (9, 'bromocriptine mesylate', 'Novartis Pharmaceuticals Corporation');
insert into Producto (idCategoria, nombre, descripcion) values (12, 'Octinoxate 7.5%', 'Melaleuca Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (3, 'buspirone hydrochloride', 'Cadila Healthcare Limited');
insert into Producto (idCategoria, nombre, descripcion) values (4, 'Desipramine Hydrochloride', 'Actavis Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (15, 'Levocarnitine', 'REMEDYREPACK INC.');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'Loratadine', 'Clinical Solutions Wholesale');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'Acetaminophen, Dextromethorphan', 'Publix Super Markets Inc');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Wild oat,', 'Apotheca Company');
insert into Producto (idCategoria, nombre, descripcion) values (4, 'Benzonatate', 'American Health Packaging');
insert into Producto (idCategoria, nombre, descripcion) values (9, 'Trolamine Salicylate', 'Wal-Mart Stores Inc');
insert into Producto (idCategoria, nombre, descripcion) values (8, 'Dimethicone, Padimate O, and Oxybenzone', 'Blistex Inc');
insert into Producto (idCategoria, nombre, descripcion) values (20, 'Magnesium hydroxide', 'Menper Distributors, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (1, 'Alprazolam', 'Aidarex Pharmaceuticals LLC');
insert into Producto (idCategoria, nombre, descripcion) values (20, 'AZITHROMYCIN', 'WOCKHARDT LIMITED');
insert into Producto (idCategoria, nombre, descripcion) values (18, 'haloperidol', 'Mylan Pharmaceuticals Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'AMLODIPINE BESYLATE', 'Cardinal Health');
insert into Producto (idCategoria, nombre, descripcion) values (10, 'Bacitracin, Neomycin, Polymyxin B', 'Meijer Distribution Inc');
insert into Producto (idCategoria, nombre, descripcion) values (11, 'HYDROCODONE BITARTRATE', 'Apotheca, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Glycerin', 'Babor Cosmetics America, Corp.');
insert into Producto (idCategoria, nombre, descripcion) values (3, 'Benzocaine', 'CVS Pharmacy');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Estradiol', 'AvPAK');
insert into Producto (idCategoria, nombre, descripcion) values (2, 'Magesium Citrate', 'Kmart Corporation');
insert into Producto (idCategoria, nombre, descripcion) values (2, 'Triclosan', 'Jets, Sets, & Elephants Beauty Corp.');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'venlafaxine hydrochloride', 'Zydus Pharmaceuticals (USA) Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (8, 'Octinoxate and Oxybenzone', 'Ventura Corporation LTD.');
insert into Producto (idCategoria, nombre, descripcion) values (4, 'Doxazosin', 'REMEDYREPACK INC.');
insert into Producto (idCategoria, nombre, descripcion) values (15, 'Bismuth Subsalicylate', 'Best Choice');
insert into Producto (idCategoria, nombre, descripcion) values (6, 'Meloxicam', 'PD-Rx Pharmaceuticals, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (10, 'Triamcinolone Hexacetonide', 'Sandoz Inc');
insert into Producto (idCategoria, nombre, descripcion) values (14, 'Diphenhydramine Hydrochloride', 'Qualitest Pharmaceuticals');
insert into Producto (idCategoria, nombre, descripcion) values (20, 'Ibuprofen', 'Publix Super Markets Inc');
insert into Producto (idCategoria, nombre, descripcion) values (10, 'SALICYLIC ACID', 'WALGREENS Co');
insert into Producto (idCategoria, nombre, descripcion) values (12, 'Standardized Meadow Fescue Grass Pollen', 'Nelco Laboratories, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Insects (whole body) cockroach mix', 'Jubilant HollisterStier LLC');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'risperidone', 'Mylan Institutional Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (7, 'Quetiapine fumarate', 'REMEDYREPACK INC.');
insert into Producto (idCategoria, nombre, descripcion) values (13, 'Pelargonium sidoides', 'Enzymatic Therapy, LLC');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Ceanothus americanus, Senna', 'Apotheca Company');
insert into Producto (idCategoria, nombre, descripcion) values (9, 'Warfarin Sodium', 'Rebel Distributors Corp');
insert into Producto (idCategoria, nombre, descripcion) values (17, 'Ananassa Resina', 'Uriel Pharmacy Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (3, 'Bupropion Hydrochloride', 'NorthStar RX LLC');
insert into Producto (idCategoria, nombre, descripcion) values (4, 'Agnus castus, Apis mellifica', 'King Bio Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (20, 'Felodipine', 'Richmond Pharmaceuticals, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (19, 'Meclizine HCl', 'L.N.K. International, Inc.');
insert into Producto (idCategoria, nombre, descripcion) values (9, 'nizatidine', 'Rebel Distributors Corp');
insert into Producto (idCategoria, nombre, descripcion) values (16, 'IPECACUANHA', 'HOMEOLAB USA INC');
insert into Producto (idCategoria, nombre, descripcion) values (20, 'AVOBENZONE, OCTINOXATE, OCTOCRYLENE', 'Gurwitch Products, LLC');
insert into Producto (idCategoria, nombre, descripcion) values (8, 'PYRITHIONE ZINC', 'Guthy-Renker LLC');
insert into Producto (idCategoria, nombre, descripcion) values (4, 'SELENIUM SULFIDE', 'Rochester Pharmaceuticals');