/* 
    100 Proveedores
*/
use pharmatic
insert into Proveedor (nombre, correo, direccion, telefono) values ('Adelaide De Meis', 'ade0@php.net', '6 Toban Avenue', 62066237);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Aubrie Beavon', 'abeavon1@imdb.com', '89 Autumn Leaf Street', 84706424);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dolli Semkins', 'dsemkins2@unicef.org', '953 Cardinal Pass', 40292690);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Tonnie Stobbe', 'tstobbe3@usatoday.com', '869 Warbler Point', 56456049);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Izzy Paschek', 'ipaschek4@blogs.com', '8 1st Place', 36896442);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Roby Churchill', 'rchurchill5@pinterest.com', '48 Village Green Place', 50469382);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Elisabet Georgeot', 'egeorgeot6@google.it', '48869 Lyons Pass', 51852099);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Alvis Bentson', 'abentson7@naver.com', '46497 Fair Oaks Road', 65317611);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Brnaba Woollett', 'bwoollett8@gnu.org', '337 Blue Bill Park Hill', 86918865);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Shanie Server', 'sserver9@vimeo.com', '58880 Armistice Alley', 76378482);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Claudelle Druhan', 'cdruhana@delicious.com', '81 Pleasure Avenue', 71804097);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Belva Tubritt', 'btubrittb@usda.gov', '27 Bowman Trail', 68214007);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Ethelbert Brotherhed', 'ebrotherhedc@taobao.com', '8405 Bobwhite Plaza', 46823047);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Jae Twinbourne', 'jtwinbourned@google.it', '67848 Dapin Trail', 38802026);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Gerry Rohfsen', 'grohfsene@washingtonpost.com', '5002 Hagan Center', 52456817);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Lilias Padrick', 'lpadrickf@freewebs.com', '153 Farragut Place', 97389714);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Giorgi Thornborrow', 'gthornborrowg@tuttocitta.it', '60547 Old Shore Pass', 27404481);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Katha Zettler', 'kzettlerh@indiatimes.com', '0469 Johnson Alley', 47955891);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Sharl Shenfish', 'sshenfishi@sciencedaily.com', '2 Carpenter Terrace', 53602550);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Burlie Dauney', 'bdauneyj@studiopress.com', '0501 Pleasure Pass', 49935187);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Lind Liccardo', 'lliccardok@gov.uk', '52 Russell Crossing', 90509011);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Kendall Samart', 'ksamartl@1688.com', '0034 East Street', 57693584);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Matthias Bydaway', 'mbydawaym@stumbleupon.com', '61147 Longview Lane', 93524609);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Helyn Groves', 'hgrovesn@columbia.edu', '58 Rieder Circle', 56959061);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Brigham Celand', 'bcelando@fastcompany.com', '17654 Atwood Avenue', 75592875);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Alfons Preece', 'apreecep@bbb.org', '19 Mosinee Road', 95414430);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Sarene Goldthorpe', 'sgoldthorpeq@dropbox.com', '8 Russell Crossing', 76358361);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Neala Laugharne', 'nlaugharner@oaic.gov.au', '093 Northview Hill', 18176340);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Charlena Threadgall', 'cthreadgalls@tripadvisor.com', '90 Artisan Lane', 60048029);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Blondy Gwyllt', 'bgwylltt@nytimes.com', '4238 Gateway Avenue', 34028457);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Sari Porrett', 'sporrettu@chronoengine.com', '8014 Glendale Drive', 74425642);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Ty Verchambre', 'tverchambrev@ihg.com', '47949 Del Mar Trail', 31947351);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Jodee Gunderson', 'jgundersonw@berkeley.edu', '776 Di Loreto Park', 97413346);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Ailee Sproson', 'asprosonx@devhub.com', '4683 School Crossing', 87258440);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Bartholomeo Welford', 'bwelfordy@youtu.be', '03719 Armistice Court', 98061463);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Alys Hasell', 'ahasellz@blogtalkradio.com', '74 Sachs Center', 16777641);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Barbey Bohlmann', 'bbohlmann10@walmart.com', '101 Service Park', 56905920);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Parker Cuckoo', 'pcuckoo11@timesonline.co.uk', '3 Mendota Way', 86541166);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Murdock Nickoll', 'mnickoll12@usda.gov', '3204 Harbort Trail', 99309935);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Alysia Carden', 'acarden13@unicef.org', '6780 Sunnyside Street', 28667580);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Wolfy Flament', 'wflament14@japanpost.jp', '82052 Pine View Plaza', 20158918);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Berenice Frost', 'bfrost15@tumblr.com', '80 Forest Court', 56263130);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dorothy MacKill', 'dmackill16@cocolog-nifty.com', '9 Carey Road', 84463747);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Denney Labes', 'dlabes17@marriott.com', '712 Corscot Crossing', 51194700);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Porter Fellows', 'pfellows18@github.io', '82 Granby Circle', 13523222);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dougie Soppit', 'dsoppit19@jalbum.net', '44154 Doe Crossing Crossing', 76370955);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Jessamine Gregoretti', 'jgregoretti1a@prlog.org', '65603 Sloan Parkway', 29972903);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Clair Bycraft', 'cbycraft1b@npr.org', '69251 Dexter Lane', 68646594);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Paco Perllman', 'pperllman1c@mashable.com', '7148 Lakeland Pass', 89709792);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dell Trillo', 'dtrillo1d@discovery.com', '383 Doe Crossing Place', 95910322);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Nevsa Nanni', 'nnanni1e@example.com', '65177 Tony Street', 20527441);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Martica Spellard', 'mspellard1f@netscape.com', '294 Jay Lane', 79698587);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Kennan Wolfart', 'kwolfart1g@nymag.com', '1961 Ryan Circle', 31979844);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Fields Caccavari', 'fcaccavari1h@ca.gov', '336 Stephen Junction', 68171800);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Bell Beesey', 'bbeesey1i@salon.com', '6 Anderson Avenue', 41147037);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Wilone Panter', 'wpanter1j@opera.com', '11 Sycamore Crossing', 92229330);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Murray Gawthorpe', 'mgawthorpe1k@ed.gov', '96 Hooker Road', 70147978);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Janey Chezier', 'jchezier1l@dmoz.org', '91 Grover Alley', 64282840);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Thain Campbell', 'tcampbell1m@elpais.com', '7256 Kim Street', 58686893);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Katerine Olyff', 'kolyff1n@dion.ne.jp', '270 Pankratz Road', 88445584);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Carl Mitchener', 'cmitchener1o@xing.com', '958 Darwin Center', 78071253);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Lelah Sattin', 'lsattin1p@people.com.cn', '08 Alpine Road', 75674000);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Umeko Brehaut', 'ubrehaut1q@indiegogo.com', '9057 Summit Plaza', 37245242);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Silvia Keld', 'skeld1r@dedecms.com', '540 Esch Plaza', 71472478);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Shelden Lott', 'slott1s@devhub.com', '8028 Thackeray Point', 73792468);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Sarine Olwen', 'solwen1t@hostgator.com', '648 Summit Avenue', 51779870);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Orelie Arnold', 'oarnold1u@phpbb.com', '3589 Morrow Trail', 38265152);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Innis Altree', 'ialtree1v@lulu.com', '744 Beilfuss Road', 57696546);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Alasteir Sprackling', 'asprackling1w@sitemeter.com', '21 Sullivan Trail', 54954059);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Ludovika Marfield', 'lmarfield1x@msn.com', '3 Gerald Avenue', 76087275);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Faulkner Laurentino', 'flaurentino1y@ucoz.ru', '81571 Veith Avenue', 69487292);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Golda Blewitt', 'gblewitt1z@creativecommons.org', '12 Pearson Road', 70137818);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Benji O''Crotty', 'bocrotty20@ning.com', '7 Fisk Circle', 40378598);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Roobbie Belchamp', 'rbelchamp21@java.com', '7908 Monterey Court', 36628750);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Antoine Blenkensop', 'ablenkensop22@webmd.com', '60148 Kensington Way', 23697914);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Chryste Kops', 'ckops23@miitbeian.gov.cn', '23 Packers Lane', 64540504);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Engelbert Sumpton', 'esumpton24@yandex.ru', '987 Dakota Terrace', 88864168);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Jeddy Caughan', 'jcaughan25@joomla.org', '209 Fulton Center', 53661319);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Fidelia Popworth', 'fpopworth26@amazon.de', '9709 Forest Circle', 66239289);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Anson Nowill', 'anowill27@diigo.com', '9562 Fairfield Drive', 27510352);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Auberta Carlon', 'acarlon28@census.gov', '431 Bowman Point', 19320905);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Tasia Ollarenshaw', 'tollarenshaw29@washington.edu', '799 Division Point', 18191424);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Marlo Way', 'mway2a@scribd.com', '9403 Briar Crest Court', 42319961);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Chan Caygill', 'ccaygill2b@about.me', '63 Mcguire Plaza', 44195637);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dael Linnane', 'dlinnane2c@harvard.edu', '7 Emmet Park', 98720958);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Nerti Trevains', 'ntrevains2d@google.it', '6738 Harbort Park', 81415659);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Darice Vanyushkin', 'dvanyushkin2e@house.gov', '3804 Orin Terrace', 97477474);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Remy Le Brum', 'rle2f@amazon.co.jp', '56342 Lawn Street', 41135540);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Joscelin Anten', 'janten2g@blogger.com', '6 Riverside Trail', 46363452);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dorella McIlreavy', 'dmcilreavy2h@bing.com', '211 Sundown Circle', 16657386);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Camey McKague', 'cmckague2i@businessinsider.com', '0075 Cambridge Place', 34737681);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Chloette O''Docherty', 'codocherty2j@wunderground.com', '0 Pond Point', 88529633);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Romola Legg', 'rlegg2k@deviantart.com', '1611 Claremont Trail', 67637951);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Berkie Pettiford', 'bpettiford2l@comsenz.com', '007 Hudson Plaza', 66866873);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Teddie Ellum', 'tellum2m@ebay.com', '94 Shoshone Park', 20043048);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Andie Braden', 'abraden2n@sbwire.com', '9 Muir Center', 86427324);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Dayna Slorance', 'dslorance2o@cafepress.com', '22 Mendota Crossing', 41325932);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Camala Buglar', 'cbuglar2p@webs.com', '74380 Huxley Place', 98389391);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Tasia Stailey', 'tstailey2q@vistaprint.com', '57862 Loomis Center', 87266791);
insert into Proveedor (nombre, correo, direccion, telefono) values ('Atlanta Easbie', 'aeasbie2r@skype.com', '04 5th Lane', 23038137);
